// const LOGIN_SUCCESS= "@Types/LOGIN_SUCCESS";
// const LOGOUT_SUCCESS = "@Types/LOGOUT_SUCCESS";
// const REGISTRATION_SUCCESS= "@Types/REGISTRATION_SUCCESS";
// export default {
//     LOGIN_SUCCESS,
//     LOGOUT_SUCCESS,
//     REGISTRATION_SUCCESS,
// };


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";