export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAILED  = "LOGIN_FAILED";
export const REGISTRATION_SUCCESS= "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL= "REGISTRATION_FAILED";
//export const GET_ERRORS= "GET_ERRORS"

export default {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAIL
}

